# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yumeiren' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for yumeiren
pod 'AFNetworking'
pod 'MJRefresh'
pod 'IQKeyboardManager', '~> 5.0.7'
pod 'MJExtension'
pod "SVProgressHUD-0.8.1"
pod 'Masonry'
pod 'SDCycleScrollView', '~> 1.80'
pod 'TYPagerController'
pod 'AMap2DMap-NO-IDFA'
pod 'AMapSearch-NO-IDFA'
pod 'AMapLocation-NO-IDFA'

end
